//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseFramework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AdminUser
    {
        public System.Guid id { get; set; }
        public string UserName { get; set; }
        public string Pwz { get; set; }
        public string PermissionInfo { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Creator { get; set; }
    }
}
